add xacro and stl for tsukuba challenge 2024
NaokiTakahashi12/unitree_go1_ros2 pull request #26
Opened 2024-12-02 13:20 UTC by kenta-kawamata

ご精査ください2

2024-12-02 13:31 UTC, kenta-kawamata commented
`go1_livox_mount.xacro`を追加し，当該ファイル中にIMUとLIVOXの中心座標を記述，各センサの中心座標はすべて`base_link`とのジョイントで定義しています．

2024-12-02 21:17 UTC, NaokiTakahashi12 requested changes

2024-12-02 21:17 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +
不要そうなら削除お願いします
必要そうなら，ifとかつける形に変更お願いします

2024-12-02 21:17 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +      <mesh filename="file://$(find unitree_go1_description_description)/meshes/visual/units/sensor_mount.stl" scale="0.001 0.001 0.001"/>
パッケージ名が誤っています，修正お願いします
unitree_go1_description_description

2024-12-02 21:17 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +<link name="mid360_link"/>
本来はこのリンク名のほうがわかりやすいですが，`livox_frame`でデータを集めてしまったので，
`livox_frame`に変更お願いします

2024-12-02 21:17 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/tc24_unitree_go1.urdf.xacro
> +  </xacro:backpack_sensor_unit>
不要なら削除お願いします

2024-12-03 12:24 UTC, kenta-kawamata commented
上記コメントを反映しました。ご確認のほどお願いいたします。

2024-12-03 14:41 UTC, NaokiTakahashi12 requested changes

2024-12-03 14:41 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +<link name="imu_link"/>
このリンク名が重複しています
`imu_link`はすでにUnitree Go1の胴体内部のIMUで使用しているので，
新規追加したIMUを指している場合は，`witmotion_imu_link`に変更お願いします．

2024-12-03 14:47 UTC, NaokiTakahashi12 commented on unitree_go1_description/meshes/visual/units/sensor_mount.stl
可視化モデルと接触モデルの両方で，ネジ穴情報付きのSTLを読み込んでしまっているので，
処理上不要なネジ穴は埋めれたら埋めときたいです

手間多そうなので，このPRでは対応不要です．

2024-12-03 14:47 UTC, NaokiTakahashi12 commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +</joint>
ソースの情報見つけられなかったですが，このZ高さは正しいですか？
大体はセンサ根本の座標がフレームになるかなと，考えていました．
![image](https://github.com/user-attachments/assets/9e393a7b-017d-4466-8273-69760e7cf2ab)

問題あっても簡単に修正できるので，わからない場合はこのPRで対応不要です．

2024-12-04 12:44 UTC, kenta-kawamata commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +</joint>
`livox_frame`は、mid-360における理想上の0点の座標を設定しています。この0点は、mid-360の底面から47.0 mmの高さにあり、`base_link`と比較すると、丁度`base_link`からZ軸に170 mmの高さに存在します。
センサのキャリブレーション結果に応じて動かしたい場合や、底面を座標としている方が良い場合は、修正します。

![Screenshot from 2024-12-04 21-43-22](https://github.com/user-attachments/assets/076e401f-a655-413a-a74c-ef7d283e3241)

2024-12-04 12:46 UTC, kenta-kawamata commented on unitree_go1_description/urdf/go1_livox_mount.xacro
> +</joint>
以下、添付画像の3面図が掲載されているマニュアル。
https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/Mid360/Livox_Mid-360_User_Manual_EN.pdf

2024-12-04 13:06 UTC, kenta-kawamata commented
imuのリンク名を修正しました。モデルに関しては、取り急ぎは接触モデルの簡素化を着手します。

2024-12-04 13:26 UTC, NaokiTakahashi12 approved these changes

2024-12-04 13:27 UTC, merged

2024-12-04 13:30 UTC, NaokiTakahashi12 commented
> imuのリンク名を修正しました。モデルに関しては、取り急ぎは接触モデルの簡素化を着手します。

計算資源的には大きな悪影響がないので，モデル改良でPRお待ちしてます．